#!/bin/sh

# Xen Hypervisor nagios check
# Arno Broekhof | 2009

# include nagios utils
. /usr/lib/nagios/plugins/utils.sh

PARM1=$1
WARN=$2
PARM2=$3
CRIT=$4

if [ "$PARM2" != "-c" -o "$CRIT" == "" ]; then
        echo "Usage: $0 -w <warning> -c <critical>"
# Nagios exit code 3 = status UNKNOWN = orange

if [ "$PARM1" != "-h" ]; then
        exit $STATE_UNKNOWN
   else
        echo ""
        echo " -w = Minimum Number of Xen VMs to activate a warning message."
        echo " -c = Number of Xen VMs to activate a critical message."
        echo " -h = This help message."
        exit 3
   fi
fi

RUNNING=$(sudo /usr/sbin/xm list | awk '!/[DN]/  {print $1 }')
NBVMS=$(echo $RUNNING | wc -w)
HNAME=$(hostname)

#echo "Xen Running =" $RUNNING

if [ "$NBVMS" -le "$CRIT" ]; then
        echo "Critical Xen VMs Usage - Total NB: $NBVMS - detected VMs: $RUNNING"
# Nagios exit code 2 = status CRITICAL = red
        exit $STATE_CRITICAL
        else if [ "$NBVMS" -le "$WARN" ]; then
           echo "Warning Xen VMs Usage - Total NB: $NBVMS - detected VMs: $RUNNING"
# Nagios exit code 1 = status WARNING = yellow
           exit $STATE_WARNING
        else
            echo "OK: Xen Hypervisor \"$HNAME\" is running Xen VMs: $RUNNING"
# Nagios exit code 0 = status OK = green
            exit $STATE_OK
        fi
fi
